# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'example.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(323, 259)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 50, 201, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.button_input = QtWidgets.QPushButton(self.centralwidget)
        self.button_input.setGeometry(QtCore.QRect(220, 50, 91, 23))
        self.button_input.setObjectName("button_input")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 90, 201, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.button_output = QtWidgets.QPushButton(self.centralwidget)
        self.button_output.setGeometry(QtCore.QRect(220, 90, 91, 23))
        self.button_output.setObjectName("button_output")
        self.button_convert = QtWidgets.QPushButton(self.centralwidget)
        self.button_convert.setGeometry(QtCore.QRect(80, 190, 121, 23))
        self.button_convert.setObjectName("button_convert")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 20, 121, 16))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.num_height = QtWidgets.QSpinBox(self.centralwidget)
        self.num_height.setGeometry(QtCore.QRect(130, 130, 71, 22))
        self.num_height.setObjectName("num_height")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 130, 51, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 160, 51, 21))
        self.label_3.setObjectName("label_3")
        self.select_type = QtWidgets.QComboBox(self.centralwidget)
        self.select_type.setGeometry(QtCore.QRect(130, 160, 71, 22))
        self.select_type.setObjectName("select_type")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 323, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_input.setText(_translate("MainWindow", "Import file"))
        self.button_output.setText(_translate("MainWindow", "Select output file"))
        self.button_convert.setText(_translate("MainWindow", "Convert"))
        self.label.setText(_translate("MainWindow", "File converter"))
        self.label_2.setText(_translate("MainWindow", "Height"))
        self.label_3.setText(_translate("MainWindow", "Type"))
